#############################################################################
# Makefile for building: wrsw_calib-qt4
# Generated by qmake (2.01a) (Qt 4.8.6) on: wt. sie 25 17:53:12 2015
# Project:  wrsw_calib-qt4.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile wrsw_calib-qt4.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = calibration.cpp \
		calibrator_ui.cpp \
		confile.cpp \
		fiber_alpha_ui.cpp \
		fiber_ui.cpp \
		labels.cpp \
		main.cpp \
		main_ui.cpp \
		oscil.cpp \
		switch.cpp \
		wr_calib.cpp moc_calibrator_ui.cpp \
		moc_fiber_alpha_ui.cpp \
		moc_fiber_ui.cpp \
		moc_main_ui.cpp \
		moc_wr_calib.cpp
OBJECTS       = calibration.o \
		calibrator_ui.o \
		confile.o \
		fiber_alpha_ui.o \
		fiber_ui.o \
		labels.o \
		main.o \
		main_ui.o \
		oscil.o \
		switch.o \
		wr_calib.o \
		moc_calibrator_ui.o \
		moc_fiber_alpha_ui.o \
		moc_fiber_ui.o \
		moc_main_ui.o \
		moc_wr_calib.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		wrsw_calib-qt4.pro
QMAKE_TARGET  = wrsw_calib-qt4
DESTDIR       = 
TARGET        = wrsw_calib-qt4

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_calibrator.h ui_fiber_alpha.h ui_fiber_lat.h ui_main_win.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wrsw_calib-qt4.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile wrsw_calib-qt4.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile wrsw_calib-qt4.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/wrsw_calib-qt41.0.0 || $(MKDIR) .tmp/wrsw_calib-qt41.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/wrsw_calib-qt41.0.0/ && $(COPY_FILE) --parents calibration.h calibrator_ui.h calibrator_ui_qt.h confile.h fiber_alpha_ui.h fiber_alpha_ui_qt.h fiber_ui.h fiber_ui_qt.h labels.h main_ui.h main_ui_qt.h oscil.h switch.h wr_calib.h .tmp/wrsw_calib-qt41.0.0/ && $(COPY_FILE) --parents calibration.cpp calibrator_ui.cpp confile.cpp fiber_alpha_ui.cpp fiber_ui.cpp labels.cpp main.cpp main_ui.cpp oscil.cpp switch.cpp wr_calib.cpp .tmp/wrsw_calib-qt41.0.0/ && $(COPY_FILE) --parents calibrator.ui fiber_alpha.ui fiber_lat.ui main_win.ui .tmp/wrsw_calib-qt41.0.0/ && (cd `dirname .tmp/wrsw_calib-qt41.0.0` && $(TAR) wrsw_calib-qt41.0.0.tar wrsw_calib-qt41.0.0 && $(COMPRESS) wrsw_calib-qt41.0.0.tar) && $(MOVE) `dirname .tmp/wrsw_calib-qt41.0.0`/wrsw_calib-qt41.0.0.tar.gz . && $(DEL_FILE) -r .tmp/wrsw_calib-qt41.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_calibrator_ui.cpp moc_fiber_alpha_ui.cpp moc_fiber_ui.cpp moc_main_ui.cpp moc_wr_calib.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calibrator_ui.cpp moc_fiber_alpha_ui.cpp moc_fiber_ui.cpp moc_main_ui.cpp moc_wr_calib.cpp
moc_calibrator_ui.cpp: calibrator_ui_qt.h \
		switch.h \
		calibrator_ui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) calibrator_ui.h -o moc_calibrator_ui.cpp

moc_fiber_alpha_ui.cpp: fiber_alpha_ui_qt.h \
		switch.h \
		oscil.h \
		fiber_alpha_ui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fiber_alpha_ui.h -o moc_fiber_alpha_ui.cpp

moc_fiber_ui.cpp: fiber_ui_qt.h \
		switch.h \
		calibration.h \
		oscil.h \
		fiber_ui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fiber_ui.h -o moc_fiber_ui.cpp

moc_main_ui.cpp: ui_main_win.h \
		fiber_ui.h \
		fiber_ui_qt.h \
		switch.h \
		calibration.h \
		oscil.h \
		fiber_alpha_ui.h \
		fiber_alpha_ui_qt.h \
		calibrator_ui.h \
		calibrator_ui_qt.h \
		main_ui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main_ui.h -o moc_main_ui.cpp

moc_wr_calib.cpp: wr_calib.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) wr_calib.h -o moc_wr_calib.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_calibrator.h ui_fiber_alpha.h ui_fiber_lat.h ui_main_win.h
compiler_uic_clean:
	-$(DEL_FILE) ui_calibrator.h ui_fiber_alpha.h ui_fiber_lat.h ui_main_win.h
ui_calibrator.h: calibrator.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic calibrator.ui -o ui_calibrator.h

ui_fiber_alpha.h: fiber_alpha.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic fiber_alpha.ui -o ui_fiber_alpha.h

ui_fiber_lat.h: fiber_lat.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic fiber_lat.ui -o ui_fiber_lat.h

ui_main_win.h: main_win.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic main_win.ui -o ui_main_win.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

calibration.o: calibration.cpp calibration.h \
		switch.h \
		oscil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibration.o calibration.cpp

calibrator_ui.o: calibrator_ui.cpp calibrator_ui.h \
		calibrator_ui_qt.h \
		switch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrator_ui.o calibrator_ui.cpp

confile.o: confile.cpp confile.h \
		switch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confile.o confile.cpp

fiber_alpha_ui.o: fiber_alpha_ui.cpp fiber_alpha_ui.h \
		fiber_alpha_ui_qt.h \
		switch.h \
		oscil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fiber_alpha_ui.o fiber_alpha_ui.cpp

fiber_ui.o: fiber_ui.cpp fiber_ui.h \
		fiber_ui_qt.h \
		switch.h \
		calibration.h \
		oscil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fiber_ui.o fiber_ui.cpp

labels.o: labels.cpp labels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o labels.o labels.cpp

main.o: main.cpp wr_calib.h \
		calibration.h \
		switch.h \
		oscil.h \
		confile.h \
		main_ui.h \
		ui_main_win.h \
		fiber_ui.h \
		fiber_ui_qt.h \
		fiber_alpha_ui.h \
		fiber_alpha_ui_qt.h \
		calibrator_ui.h \
		calibrator_ui_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_ui.o: main_ui.cpp main_ui.h \
		ui_main_win.h \
		fiber_ui.h \
		fiber_ui_qt.h \
		switch.h \
		calibration.h \
		oscil.h \
		fiber_alpha_ui.h \
		fiber_alpha_ui_qt.h \
		calibrator_ui.h \
		calibrator_ui_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_ui.o main_ui.cpp

oscil.o: oscil.cpp oscil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oscil.o oscil.cpp

switch.o: switch.cpp switch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switch.o switch.cpp

wr_calib.o: wr_calib.cpp wr_calib.h \
		fiber_ui.h \
		fiber_ui_qt.h \
		switch.h \
		calibration.h \
		oscil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wr_calib.o wr_calib.cpp

moc_calibrator_ui.o: moc_calibrator_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrator_ui.o moc_calibrator_ui.cpp

moc_fiber_alpha_ui.o: moc_fiber_alpha_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fiber_alpha_ui.o moc_fiber_alpha_ui.cpp

moc_fiber_ui.o: moc_fiber_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fiber_ui.o moc_fiber_ui.cpp

moc_main_ui.o: moc_main_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_ui.o moc_main_ui.cpp

moc_wr_calib.o: moc_wr_calib.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wr_calib.o moc_wr_calib.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

